feat: Handling entry fragment backstack
feat: Handling entry fragment backstack
- Handled the fragment backstack using Jetpack navigation; Prevented erroneous logic - such as going back to splash screen from SignInFragment etc
- Added fading animation during transitions
- Seperated responsibility of EntryActivity  even further. Passed the initial control flow of fragment to EntryFragment; Considered EntryActivity as the one with  sole authority of launching MainActivity, and used Fragment Result API to facilitate fragment main activity launch request.
- Accounted for screen rotations while implementing except for the below scenario.

error: SignInFragment Screen rotation
- When Screen rotates when the snackbar is shown, I think the callback tries to find the  previous fragment manager , when the new one is being used. ( Snackbar callback - onDismissal is used launch the subsequent fragment)